#static/admin/config.yml

backend:
  name: git-gateway
  branch: main

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}/index" #Each document is inside a folder with the slug name.
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayınlanma Tarihi", name: "date", widget: "datetime" }
      - { label: "Tanıtım Yazısı", name: "description", widget: "text"}
      - { label: "Öne Çıkan Görsel", name: "image", widget: "image", required: false }
      - { label: "Etiketler", name: "tags", widget: "list", summary: "{{fields.tag}}", field: { label: "Tag", name: "tag", widget: "string" }} # https://github.com/decaporg/decap-cms/issues/4646 
      - { label: "Gövde", name: "body", widget: "markdown", hint: "Make sure to name added image as thumbnail" }
